import Sidebar from '@/components/sidebar'
import './globals.css'
import { Gothic_A1 } from 'next/font/google'
import clsx from 'clsx'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Gothic_A1({
  weight: ["400", "700"],
})


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <div className={clsx('flex flex-row w-[1000px] bg-zinc-100 mx-auto')}>
          <Sidebar />
          <main>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
